---
apiVersion: v1
kind: ConfigMap
metadata:
  name: janusgraph-tablestore-config
  namespace: janusgraph
data:
  janusgraph-tablestore-server.properties: |+
    gremlin.graph=org.janusgraph.core.JanusGraphFactory
    storage.backend=tablestore
    storage.hbase.ext.hbase.client.connection.impl=com.alicloud.tablestore.hbase.TablestoreConnection
    storage.hbase.ext.tablestore.client.endpoint=https://jg-test.ap-southeast-5.ots.aliyuncs.com:443
    storage.hbase.ext.tablestore.client.instancename=jg-test
    storage.hbase.ext.tablestore.client.accesskeyid=xxx
    storage.hbase.ext.tablestore.client.accesskeysecret=xxx
    storage.hbase.ext.hbase.client.tablestore.table=test_table
    storage.hbase.ext.hbase.defaults.for.version.skip=true
    storage.hbase.ext.hbase.hconnection.meta.lookup.threads.core=4
    storage.hbase.ext.hbase.hconnection.threads.keepalivetime=3
    storage.hbase.ext.hbase.client.tablestore.family=s

    graph.assign-timestamp=false
    graph.timestamps=NANO
    graph.allow-upgrade=false
    graph.allow-stale-config=true
    graph.replace-instance-if-exists: true

    query.batch: true
    query.limit-batch-size: true

    schema.constraints: true
    schema.default: none

    cluster.max-partitions: 1024

    ids.block-size: 1000000

    storage.lock.wait-time=1000
    storage.batch-loading: false
    storage.hbase.scan.parallelism: 10

    cache.db-cache=true
    cache.db-cache-clean-wait=20
    cache.db-cache-time=180000
    cache.db-cache-size=0.5

    metrics.merge-stores: false
    metrics.enabled: false
    metrics.jmx.enabled: false

  janusgraph-server.yaml: |+
    host: 0.0.0.0
    port: 8182
    channelizer: org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer
    graphs: {
      graph: conf/janusgraph-tablestore-server.properties
    }

    evaluationTimeout: 50000
    maxInitialLineLength: 4096
    maxHeaderSize: 8192
    maxChunkSize: 8192
    maxContentLength: 65536
    maxAccumulationBufferComponents: 1024
    resultIterationBatchSize: 64
    writeBufferLowWaterMark: 32768
    writeBufferHighWaterMark: 65536
    useEpollEventLoop: true
    useCommonEngineForSessions: true
    useGlobalFunctionCacheForSessions: false
    maxParameters: 128
    maxSessionTaskQueueSize: 1024
    maxWorkQueueSize: 1024

    scriptEngines: {
      gremlin-groovy: {
        plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
                  org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
                  org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
                  org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
                  org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]},
                  org.apache.tinkerpop.gremlin.groovy.jsr223.GroovyCompilerGremlinPlugin: {enableThreadInterrupt: true, expectedCompilationTime: 10, globalFunctionCacheEnabled: false}}}}

    serializers:
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1, config: { serializeResultToString: true }}
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV3, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
      # Older serialization versions for backwards compatibility:
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV2, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONUntypedMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}

    # processors:
    #   - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000, maxParameters: 64 }}
    #   - { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
    #   - { className: org.apache.tinkerpop.gremlin.server.op.standard.StandardOpProcessor, config: { maxParameters: 64 }}

    # metrics: {
    #   consoleReporter: {enabled: false, interval: 180000},
    #   csvReporter: {enabled: false, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
    #   jmxReporter: {enabled: true},
    #   slf4jReporter: {enabled: {{ .Values.janusgraphServer.metrics.slf4jReporter.enabled }}, interval: {{ .Values.janusgraphServer.metrics.slf4jReporter.intervalMS }} },
    #   gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
    #   graphiteReporter: {enabled: false, interval: 180000}}
  
  remote.yaml: |+
    hosts: [localhost]
    port: 8182
    serializer: { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1, config: { serializeResultToString: true }}
