---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janusgraph-tablestore
  namespace: janusgraph
spec:
  replicas: 2
  selector:
    matchLabels:
      app: janusgraph-tablestore
  template:
    metadata:
      labels:
        app: janusgraph-tablestore
    spec:
      containers:
      - name: janusgraph-tablestore
        image: janusgraph/janusgraph:1.0.0
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "8Gi"
            cpu: "8"
        ports:
        - containerPort: 8182  # JanusGraph default port
        volumeMounts:
        - name: janusgraph-tablestore-config
          mountPath: /opt/janusgraph/conf/janusgraph-tablestore-server.properties
          subPath: janusgraph-tablestore-server.properties
        - name: janusgraph-tablestore-config
          mountPath: /opt/janusgraph/conf/janusgraph-server.yaml
          subPath: janusgraph-server.yaml
        env:
        - name: JANUS_PROPS_TEMPLATE
          value: tablestore
        readinessProbe:
          httpGet:
            path: /?gremlin=100-1
            port: 8182
          initialDelaySeconds: 0
          periodSeconds: 2
          timeoutSeconds: 1
        # startupProbe:
        #   httpGet:
        #     path: /?gremlin=100-1
        #     port: 8182
        #   initialDelaySeconds: 60
        #   failureThreshold: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 1
        # livenessProbe:
        #   tcpSocket:
        #     port: 8182
        #   initialDelaySeconds: 30
        #   failureThreshold: 3
        #   periodSeconds: 10
        #   timeoutSeconds: 1
      volumes:
      - name: janusgraph-tablestore-config
        configMap:
          name: janusgraph-tablestore-config
