---
apiVersion: v1
kind: ConfigMap
metadata:
  name: janusgraph-lindorm-config
  namespace: janusgraph
data:
  janusgraph-lindorm-server.properties: |+
    gremlin.graph=org.janusgraph.core.JanusGraphFactory
    storage.backend: hbase
    storage.directory: null
    storage.read-only: false
    storage.hbase.table: test-lindorm
    storage.hostname: ld-d9j575h5ta418e5nk-proxy-lindorm.lindorm.rds.aliyuncs.com:30020
    storage.hbase.ext.hbase.client.username: xxx
    storage.hbase.ext.hbase.client.password: xxx

    cache.db-cache: false
    cache.db-cache-clean-wait: 20
    cache.db-cache-time: 180000
    cache.db-cache-size: 0
    cluster.max-partitions: 1024
    graph.replace-instance-if-exists: true
    metrics.enabled: false
    metrics.jmx.enabled: false
    ids.block-size: 1000000
    query.batch.enabled: true
    query.batch.limited: true
    schema.constraints: true
    schema.default: none
    storage.batch-loading: false
    storage.hbase.scan.parallelism: 10
    metrics.merge-stores: false

  janusgraph-server.yaml: |+
    host: 0.0.0.0
    port: 8182
    channelizer: org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer
    graphs: {
      graph: conf/janusgraph-lindorm-server.properties
    }

    evaluationTimeout: 50000
    maxInitialLineLength: 4096
    maxHeaderSize: 8192
    maxChunkSize: 8192
    maxContentLength: 65536
    maxAccumulationBufferComponents: 1024
    resultIterationBatchSize: 64
    writeBufferLowWaterMark: 32768
    writeBufferHighWaterMark: 65536
    useEpollEventLoop: true
    useCommonEngineForSessions: true
    useGlobalFunctionCacheForSessions: false
    maxParameters: 128
    maxSessionTaskQueueSize: 1024
    maxWorkQueueSize: 1024

    scriptEngines: {
      gremlin-groovy: {
        plugins: { org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
                  org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
                  org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
                  org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {classImports: [java.lang.Math], methodImports: [java.lang.Math#*]},
                  org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {files: [scripts/empty-sample.groovy]},
                  org.apache.tinkerpop.gremlin.groovy.jsr223.GroovyCompilerGremlinPlugin: {enableThreadInterrupt: true, expectedCompilationTime: 10, globalFunctionCacheEnabled: false}}}}

    serializers:
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1, config: { serializeResultToString: true }}
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV3, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
      # Older serialization versions for backwards compatibility:
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV2, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
      - { className: org.apache.tinkerpop.gremlin.util.ser.GraphSONUntypedMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}

    processors:
      - { className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor, config: { sessionTimeout: 28800000, maxParameters: 64 }}
      - { className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor, config: { cacheExpirationTime: 600000, cacheMaxSize: 1000 }}
      - { className: org.apache.tinkerpop.gremlin.server.op.standard.StandardOpProcessor, config: { maxParameters: 64 }}

    metrics: {
      consoleReporter: {enabled: false, interval: 180000},
      csvReporter: {enabled: false, interval: 180000, fileName: /tmp/gremlin-server-metrics.csv},
      jmxReporter: {enabled: true},
      slf4jReporter: {enabled: true, interval: 120000 },
      gangliaReporter: {enabled: false, interval: 180000, addressingMode: MULTICAST},
      graphiteReporter: {enabled: false, interval: 180000}}
  
  remote.yaml: |+
    hosts: [localhost]
    port: 8182
    serializer: { className: org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1, config: { serializeResultToString: true }}

  log4j-server.properties: |+
    log4j.appender.console=org.apache.log4j.ConsoleAppender
    log4j.appender.console.Threshold=INFO
    log4j.appender.console.layout=biz.paluch.logging.gelf.log4j.GelfLayout
    log4j.appender.console.layout.ConversionPattern='{"timestamp":"%d{ISO8601}","level":"%p","thread":"%t","logger":"%c","message":"%m","exception":"%throwable{1000}"}%n'
    log4j.appender.console.layout.ExtractStackTrace=true
    log4j.category.com.google.cloud.bigtable.metrics=DEBUG
    log4j.rootLogger="INFO, console"
