---
apiVersion: v1
kind: Service
metadata:
  name: janusgraph-lindorm-service
  namespace: janusgraph
  labels:
    app: janusgraph-lindorm
spec:
  selector:
    app: janusgraph-lindorm  # This matches the label in your Deployment
  ports:
    - name: janusgraph-lindorm
      protocol: TCP
      port: 8182       # Port exposed by the service
      targetPort: 8182  # Port where JanusGraph is running in the container
  type: ClusterIP  # Default service type, you can change it to LoadBalancer or NodePort if needed